const { SlashCommandBuilder, ContainerBuilder, SeparatorBuilder, SeparatorSpacingSize, ButtonBuilder, ButtonStyle, ActionRowBuilder, MessageFlags } = require('discord.js');

const VERIFIED_ROLE_ID = '1353884132244983880';
const DIVIDER = '\u200b';

module.exports = {
  data: new SlashCommandBuilder()
    .setName('start-here')
    .setDescription('Send the start-here message to the channel'),

  buttonData: { customId: 'verify_button' },

  async execute(interaction) {
    if (!interaction.guild) return;
    const member = await interaction.guild.members.fetch(interaction.user.id).catch(() => null);
    if (!member?.permissions.has('Administrator')) {
      return interaction.reply({ content: '❌ Admins only.', flags: 64 });
    }

    await interaction.reply({ content: '✅ Sending start-here message...', flags: 64 }).catch(() => {});

    const send = async (container) => {
      try {
        await interaction.channel.send({ components: [container], flags: MessageFlags.IsComponentsV2 });
      } catch (err) { console.error('Send error:', err.message); }
      await new Promise(r => setTimeout(r, 800));
    };

    const sendDivider = async () => {
      try { await interaction.channel.send({ content: DIVIDER }); } catch {}
      await new Promise(r => setTimeout(r, 800));
    };

    // Message 1 — Intro + image
    await send(new ContainerBuilder()
      .addTextDisplayComponents(t => t.setContent('## Intro to the Server'))
      .addMediaGalleryComponents(g => g.addItems(i => i.setURL('https://i.imgur.com/PEc3pFU.jpeg')))
      .addTextDisplayComponents(t => t.setContent(
        'Welcome to **Block Party** — a community built around free Minecraft Bedrock content.\n\n' +
        'Read through the sections below before diving in.'
      ))
    );

    await sendDivider();

    // Message 2 — Arges Bot
    await send(new ContainerBuilder()
      .addTextDisplayComponents(t => t.setContent('## ARGES MARKETPLACE BOT'))
      .addTextDisplayComponents(t => t.setContent(
        'Download Minecraft Marketplace content directly — add-ons, worlds, texture packs, skin packs, everything.\n\n' +
        '**Channel:** https://discord.com/channels/1353884132244983878/1469793095188217958'
      ))
      .addSeparatorComponents(s => s.setDivider(true).setSpacing(SeparatorSpacingSize.Small))
      .addTextDisplayComponents(t => t.setContent('**IMPORTANT**'))
      .addTextDisplayComponents(t => t.setContent(
        '→ Bot instructions are pinned in the channel\n\n' +
        '→ Content generated by the bot is **wiped randomly** to keep the channel clean\n\n' +
        '→ Generated download links **do not expire**'
      ))
    );

    await sendDivider();

    // Message 3 — Mod Library
    await send(new ContainerBuilder()
      .addTextDisplayComponents(t => t.setContent('## MOD LIBRARY'))
      .addTextDisplayComponents(t => t.setContent(
        'Every time someone runs the bot, the output is __automatically saved__ to the library.\n\n' +
        'If the bot channel has been wiped or you want a faster download without running any commands — check here first.\n\n' +
        '**Library:** https://discord.com/channels/1353884132244983878/1452102915769499699'
      ))
      .addSeparatorComponents(s => s.setDivider(true).setSpacing(SeparatorSpacingSize.Small))
      .addTextDisplayComponents(t => t.setContent(
        '→ Links saved here do not expire\n\n' +
        '→ No need to rerun commands if your content is already there'
      ))
    );

    await sendDivider();

    // Message 4 — Website
    await send(new ContainerBuilder()
      .addTextDisplayComponents(t => t.setContent('## THE WEBSITE'))
      .addTextDisplayComponents(t => t.setContent(
        'We have a dedicated website — login info and details are in the announcements channel.\n\n' +
        '**Login & server info:** https://discord.com/channels/1353884132244983878/1469899165608841287/1485115101173256314\n\n' +
        '**Website questions, feedback & bug reports:** https://discord.com/channels/1353884132244983878/1485125667027947792'
      ))
      .addSeparatorComponents(s => s.setDivider(true).setSpacing(SeparatorSpacingSize.Small))
      .addTextDisplayComponents(t => t.setContent(
        '→ The website is still being developed — expect updates and occasional bugs'
      ))
    );

    await sendDivider();

    // Message 5 — Verify button
    const verifyButton = new ButtonBuilder()
      .setCustomId('verify_button')
      .setLabel('✅ I have read the above — Verify me')
      .setStyle(ButtonStyle.Success);

    const row = new ActionRowBuilder().addComponents(verifyButton);

    const verifyContainer = new ContainerBuilder()
      .addTextDisplayComponents(t => t.setContent('## Verify to Access the Server'))
      .addTextDisplayComponents(t => t.setContent(
        'By clicking the button below you confirm you have read the above and agree to the server rules.\n\n' +
        'You will be granted access to the rest of the server.'
      ))
      .addActionRowComponents(() => row);

    try {
      await interaction.channel.send({ components: [verifyContainer], flags: MessageFlags.IsComponentsV2 });
    } catch (err) { console.error('Verify msg error:', err.message); }
  },

  async handleButton(interaction) {
    if (interaction.customId !== 'verify_button') return;

    const member = await interaction.guild.members.fetch(interaction.user.id).catch(() => null);
    if (!member) return interaction.reply({ content: '❌ Could not find you in the server.', flags: 64 });

    if (member.roles.cache.has(VERIFIED_ROLE_ID)) {
      return interaction.reply({ content: 'You are already verified.', flags: 64 });
    }

    await member.roles.add(VERIFIED_ROLE_ID).catch(err => console.error('Role add error:', err.message));
    return interaction.reply({ content: '✅ You have been verified! Welcome to Block Party.', flags: 64 });
  }
};